export const questionnaire = {
    acca: '1. The foods that chatbot recommends to me matches my preferences and health conditions.',
    expa: '2. I am satisfied with the images of the recommended foods.',
    expb: '3. The text explanation of the food recommendations was sufficient for me to make a decision.',
    expc: '4. I understand why the foods were recommended to me.',
    intera: '5. I found it easy to inform the chatbot what I like or dislike.',
    usefa: '6. The chatbot gave me good dietary suggestions.',
    usefb: '7. Following the dietary suggestions from the chatbot is easy.',
    trusta: '8. I am convinced of what the chatbot recommends to me.',
    trustb: '9. The chatbot can be trusted.',
    eata: '10. I would like to eat the foods that the chatbot recommended in the following days.',
    extra: '11. I do not understand why chatbot recommended the foods to me.',
    useia: '12. I would like to use the chatbot for dietary recommendations again.',
    useib: '13. I would like to use the chatbot for dietary recommendations frequently if possible.',
    useic: '14. I would like to tell my friends about this chatbot for dietary recommendations.',
    quaa: '15. Overall, I am satisfied with the recommended foods',
    ada: '16. During the conversation, the chatbot is able to detect my intention and feelings, and responds appropriately, such as switching topics and changing expressions.',
    adb: '17. I enjoy the conversation with the chatbot.',
    cusa: '18. I found the customized chatbot (e.g., personality, conversational style, and additional characteristics) talk in a way I like.',
    cusb: '19. I found customizing the chatbot is easy and effortless.',
    cusc: '20. I found customizing the chatbot is interesting.',
    q1: '21. What is your highest level of education?',
    q2: "22. Which of the following best describes your focus of work?",
    q3: '23. Which race/ethnicity best describes you?',
    q4: '24. Which of the following words is closer to your personality?',
    q5: '25. Do you have any additional thoughts and feedback on this chatbot-based recommender system? (more than 5 words)',
    botstyle: '18. I found the chatbot talk in a way I like.',
    time: '18. The chatbot responded to my messages in a reasonable timeframe, and my overall interaction experience was smooth.',
    q1bl: '19. What is your highest level of education?',
    q2bl: "20. Which of the following best describes your focus of work?",
    q3bl: '21. Which race/ethnicity best describes you?',
    q4bl: '22. Which of the following words is closer to your personality?',
    q5bl: '22. Please provide your additional thoughts and feedback on this chatbot-based recommender system here (more than 5 words)',
};