export const warnsents = {
    notfinish: 'Please complete all the screening questions before proceeding to the survey.',
    notqali: 'Sorry :( It looks like you do not meet the study criteria.',
    age: 'Please enter a valid age (over 18 and below 120).',
    height: 'Please enter a valid height (over 100cm and below 220cm).',
    weight: 'Please enter a valid weight (over 30kg and below 150kg).',
    name: 'Please enter your nickname.',
    email: 'Please enter a valid email address.',
    gender: 'Please select a valid biological sex.',
    country: 'Please select a valid country name.',
    region: 'Please select a valid region name.',
    rec: 'Please rate and review the recommendation quality.',
    int: 'Please rate and review the chatbot intelligence.',
    exp: 'Please rate and review your interacting experience.',
    edu: 'Please provide some information about your education level.',
    work: 'Please provide some information about your focus of work.',
    ra: "Please provide some information about your ethnicity, if you do not want to tell us about this, please select 'Prefer not to say'.",
    cusp: "Please select the personality to customize the chatbot according to your preference.",
    cuss: "Please select the speaking style to customize the chatbot according to your preference.",
    cusiden: "Please select the identity to customize the chatbot according to your preference.",
};